export const KEYWORD: string[] = [
  "Quỹ khuyến học",
  "Đăng ký học phần",
  "Chứng chỉ",
  "Hỗ trợ học phí",
  "Đóng học phí",
  "Học bổng",
  "Cấu trúc mail CTUT",
  "Đào tạo",
  "Rút học phần",
  "Đăng ký học lại",
  "Nghĩ học",
  "Xếp hạng năm đào tạo",
  "Xếp loại học lực",
  "Nghỉ học tạm thời",
  "Cảnh báo học vụ",
  "Đình chỉ học vụ",
  "Buộc thôi học",
  "Học song ngành",
  "Chuyển trường",
  "Kiểm tra và thi học phần",
  "Xét và công nhận tốt nghiệp",
  "Xử lí vi phạm",
  "Giới thiệu trường",
  "Phòng ban",
  "Khoa",
  "Trung tâm",
  "Đối tượng được cấp học bổng",
  "Những học kỳ được xét học bổng",
  "Tiêu chuẩn cấp học bổng",
  "Xếp loại học bổng khuyến khích học tập",
  "Thời gian cấp học bổng",
  "Phương thức nhận học bổng",
  "Giá trị học bổng",
  "loại học bổng",
  "Mail sinh viên có cấu trúc như thế nào",
  "Mail sinh viên",
  "Mail giảng viên",
  "Thời gian đào tạo trình độ đại học là bao lâu",
  "Học phần là gì",
  "Có mấy loại học phần",
  "Học phần bắt buộc là gì",
  "Học phần tự chọn là gì",
  "Học phần tiên quyết là gì",
  "Học phần học trước là gì",
  "Học phần song hành là gì",
  "Học phần tương đương, học phần thay thế là gì",
  "Học phần điều kiện là gì",
  "Tín chỉ là gì",
  "Một tiết học dài bao nhiêu",
  "Mỗi ngày có bao nhiêu tiết học",
  "Vắng học có bị cấm thi",
  "Thang điểm chữ",
  "Một năm học có bao nhiêu học kỳ",
  "Thời gian đào tạo tối đa là bao nhiêu",
  "Lớp học phần là gì",
  "Số lượng sinh viên tối thiểu của một lớp học phần",
  "Lớp sinh viên là gì",
  "Lớp sinh viên giải thế",
  "Cố vấn học tập là gì",
  "Số tín chỉ tối thiểu trong mỗi học kỳ",
  "Rút học phần là gì",
  "Thời gian được phép rút học phần",
  "Điều kiện rút bớt các học phần đã đăng ký",
  "Trường hợp phải đăng kí học lại",
  "Cải thiện điểm",
  "Học cải thiện",
  "Lựa chọn điểm xét tốt nghiệp",
  "Xếp hạng năm đào tạo",
  "Học lực",
  "XẾP LOẠI HỌC LỰC",
  "Học lực xuất sắc",
  "Học lực giỏi",
  "Học lực khá",
  "Học lực trung bình",
  "Học lực loại yếu",
  "Kết quả học tập học kỳ phụ",
  "Nghĩ học tạm thời",
  "Cảnh báo học vụ",
  "Đình chỉ học tập",
  "Buộc thôi học",
  "Học cùng lúc hai chương trình",
  "Điều kiện học cùng lúc hai chương trình",
  "Thời gian học chương trình thứ hai",
  "Điều kiện xét tốt nghiệp chương trình thứ hai",
  "Học song ngành",
  "Chứng chỉ hai",
  "CHUYỂN TRƯỜNG",
  "Điều kiện được xét chuyển trường",
  "Không được phép chuyển trường",
  "Cách tính điểm học phần",
  "Hình thức thi",
  "Bảo quản bài thi",
  "Thi vấn đáp",
  "Vắng thi",
  "Kỳ thi phụ",
  "Cách tính điểm đánh giá",
  "Cách tính điểm trung bình chung",
  "Điểm học phần được tính như thế nào",
  "Thời gian ôn thi",
  "THỜI GIAN LÀM LUẬN VĂN TỐT NGHIỆP",
  "Đối tượng làm luận văn",
  "Làm tiểu luận",
  "Học thay thế",
  "Thực tập tốt nghiệp",
  "Điều kiện xét tốt nghiệp",
  "Thời gian xét tốt nghiệp",
  "Bằng tốt nghiệp",
  "Loại bằng tốt nghiệp",
  "Hạ loại tốt nghiệp",
  "LIỆT KÊ PHÒNG BAN",
  "Phòng đào tạo",
  "Phòng công tác Chính trị và Quản lý sinh viên",
  "Phòng nghiên cứu khoa học",
  "Phòng đảm bảm chất lượng và khảo thí",
  "Phòng tổ chức hành chính",
  "Phòng quản trị thiết bị",
  "Phòng tài chính kế toán",
  "Trường có bao nhiêu ngành học",
  "Trường có bao nhiêu khoa",
  "Trường có bao nhiêu trung tâm",
];
